language: node_js
dist: trusty
install:
- npm install -s -q
before_install:
- rm -rf node_modules
- npm i -g babel-cli webpack truffle-contract
after_success:
- |
  if [ ${TRAVIS_BRANCH} = "master" ]; then
    export GNOSIS_ENV=staging;
    export NODE_ENV=production;
  else
    export GNOSIS_ENV=production;
    export NODE_ENV=production;
  fi
- npm run build
deploy:
- provider: s3
  bucket: management-development
  secret_access_key:
    secure: i+va0a6oPvU/i5Xa5gU2o36WgoaN3W2veIxtNHtxBg0km3sl8ZGZ/umwvn7SsnsUzsyVuGi3zZfmca5qLmxngvoRhijgItOBywL2lnDwGBcH5Gxph/7401XFN8IO3SpARBS01oLSBdA4rrCPCX3CrMcNoSQNxTuAHOKsEFVplK77Cdb1Q95mbo5lmYR1bfsHj4lJe6B9bq8UN+LsIYGqX2YDzNtVeNTzaitaK8SkO23UNf1eeSndBRtWi3lfTd1K/QyR3K8sEMdFL/zvkVxduez6ABO6TvfGlceuHMhYrY0h/Unw3tDI2i5614ViByhIr+Fn214g2Ior9CPnY1mO7zfOkEy0fknHA2fSwzVQClJGJHqZsvSYvUfeuBvDAXqPLklQRXOeugBamoRc3N49sMRJoyRwyBiMK4b7VWrnJ48uPk3LwMpMYy05ToMQu1IhzuOeFbok2JhSePD/FEw98+76haFzNqQ/Zntt0UhGROtH+mvPzcbBk9CXjyeGLNmPVvwPhhOQVUnLL2vL6wWHcA8/MwfwE6HL0LwcfaBc2/sSihXWkfoABUGNt7HhHHrg1ubDAb4CSwKi5PbC67QsUwFhMVIlc7LN2s2amQn+3N4Vd4RZO8iqcwQUaaRecWsdtuvk8sym958HByr3NEhTdYjnmUJKbNSHn60Z+Zun7KE=
  access_key_id:
    secure: LjkMioUBLc8j943C186OLjPz9DbEsPJHwdJ1awqDaE0K40dQmWzROP0R3Px3qW8AOnvWmXrhGSYJWY/LbAH+NFhIbPGMlQDLp8kLYmdwW0xvxokprbP4gh2MZQoV4SOdeXSGcpR61LxFlbVubS/RARJ9tVrPtHcMgKqlF75zB65Y+4rSSkRLLIe57jAegpizmOMxdetIyQ2++KqZiZplh8+OIwyTYo/jcOHrJ6pNm+cvzPVD9Ccn0ndEsDYl2u92Ev4lKUqiNA7glfQ2BP8S3omzJhU+VESDWSZyTWsVT3jGVRU3OkHrVYsmKsDdSsVu8lBp6Bso+i5hSN+H52awYI2wYzwpxiExp6jCs6n13fslYOSMDbrtL8Zqa+cq5RCXtF5j4kaHbyhEYgo4ZKYC0r/rSDYG2Co6R8m0ortNEL6oLwAKZsphTP+jVjd0ML+XoNv3XvPfdtA6YXlsIcIh49ixfqPUWbKlTF7dFBfVePvI5bnjh13PGSFggGSrGar0h5mw4r+s8OMvmaWD1yKEd0IbRcYkqjkp0yikIymZtBr9oRDnevJZTM387p02VSxPmFKShLbj7FB4nHx9Dn0XeMVS/Io10s+xTxTD4jV5UeXZacNDTCReiCMU9JhGfQ4LdMDPJp3lIFQWc3JiGjaC8nmWMKBo6Q7L8G3cfadTDU8=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: development
- provider: s3
  bucket: management-staging
  secret_access_key:
    secure: i+va0a6oPvU/i5Xa5gU2o36WgoaN3W2veIxtNHtxBg0km3sl8ZGZ/umwvn7SsnsUzsyVuGi3zZfmca5qLmxngvoRhijgItOBywL2lnDwGBcH5Gxph/7401XFN8IO3SpARBS01oLSBdA4rrCPCX3CrMcNoSQNxTuAHOKsEFVplK77Cdb1Q95mbo5lmYR1bfsHj4lJe6B9bq8UN+LsIYGqX2YDzNtVeNTzaitaK8SkO23UNf1eeSndBRtWi3lfTd1K/QyR3K8sEMdFL/zvkVxduez6ABO6TvfGlceuHMhYrY0h/Unw3tDI2i5614ViByhIr+Fn214g2Ior9CPnY1mO7zfOkEy0fknHA2fSwzVQClJGJHqZsvSYvUfeuBvDAXqPLklQRXOeugBamoRc3N49sMRJoyRwyBiMK4b7VWrnJ48uPk3LwMpMYy05ToMQu1IhzuOeFbok2JhSePD/FEw98+76haFzNqQ/Zntt0UhGROtH+mvPzcbBk9CXjyeGLNmPVvwPhhOQVUnLL2vL6wWHcA8/MwfwE6HL0LwcfaBc2/sSihXWkfoABUGNt7HhHHrg1ubDAb4CSwKi5PbC67QsUwFhMVIlc7LN2s2amQn+3N4Vd4RZO8iqcwQUaaRecWsdtuvk8sym958HByr3NEhTdYjnmUJKbNSHn60Z+Zun7KE=
  access_key_id:
    secure: LjkMioUBLc8j943C186OLjPz9DbEsPJHwdJ1awqDaE0K40dQmWzROP0R3Px3qW8AOnvWmXrhGSYJWY/LbAH+NFhIbPGMlQDLp8kLYmdwW0xvxokprbP4gh2MZQoV4SOdeXSGcpR61LxFlbVubS/RARJ9tVrPtHcMgKqlF75zB65Y+4rSSkRLLIe57jAegpizmOMxdetIyQ2++KqZiZplh8+OIwyTYo/jcOHrJ6pNm+cvzPVD9Ccn0ndEsDYl2u92Ev4lKUqiNA7glfQ2BP8S3omzJhU+VESDWSZyTWsVT3jGVRU3OkHrVYsmKsDdSsVu8lBp6Bso+i5hSN+H52awYI2wYzwpxiExp6jCs6n13fslYOSMDbrtL8Zqa+cq5RCXtF5j4kaHbyhEYgo4ZKYC0r/rSDYG2Co6R8m0ortNEL6oLwAKZsphTP+jVjd0ML+XoNv3XvPfdtA6YXlsIcIh49ixfqPUWbKlTF7dFBfVePvI5bnjh13PGSFggGSrGar0h5mw4r+s8OMvmaWD1yKEd0IbRcYkqjkp0yikIymZtBr9oRDnevJZTM387p02VSxPmFKShLbj7FB4nHx9Dn0XeMVS/Io10s+xTxTD4jV5UeXZacNDTCReiCMU9JhGfQ4LdMDPJp3lIFQWc3JiGjaC8nmWMKBo6Q7L8G3cfadTDU8=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
